name: FCIConomy
version: 1.0
author: Filip Zocktan & HappyHappyBoy
main: de.teamfci.fciconomy.FCIConomy
commands:
  fcico:
    description: Zeigt Plugininfo an
  splitter:
    description: Oeffnet Blutsplitter-Interface.